-- MySQL Script generated by MySQL Workbench
-- Sun Sep 19 21:08:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema movienote
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `movienote` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `movienote` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `movienote` ;

-- -----------------------------------------------------
-- Table `external_id`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `external_id` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `external_id` (
  `id` BIGINT NOT NULL,
  `external_id` BIGINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `genres` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `genres` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `genres` VARCHAR(245) NOT NULL,
  `external_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `movies` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `adult` BOOLEAN NOT NULL,
  `backdrop_path` VARCHAR(1245) NOT NULL,
  `original_language` VARCHAR(45) NOT NULL,
  `original_title` VARCHAR(1245) NOT NULL,
  `overview` VARCHAR(1245) NOT NULL,
  `genres_ids` VARCHAR(1245) NOT NULL,
  `external_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `movies_has_genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies_has_genres` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `movies_has_genres` (
  `movies_id` BIGINT NOT NULL,
  `genres_id` INT NOT NULL,
  PRIMARY KEY (`movies_id`, `genres_id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `roles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `roles` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `roles` VARCHAR(225) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `status` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(245) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `users_has_movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users_has_movies` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `users_has_movies` (
  `users_id` BIGINT NOT NULL,
  `description` TEXT NULL,
  `rating` INT NULL,
  `status_id` BIGINT NOT NULL,
  `movies_id` BIGINT NOT NULL,
  `created_timestamp` TIMESTAMP NOT NULL,
  `modefied_timestamp` TIMESTAMP NULL,
  PRIMARY KEY (`users_id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `users_has_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users_has_roles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `users_has_roles` (
  `users_id` BIGINT NOT NULL,
  `roles_id` BIGINT NOT NULL,
  PRIMARY KEY (`users_id`, `roles_id`));

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
